# Site settings 配置站点
title: '佩奇の家'
description: 'JUST DO IT'
keywords: 'React web , JavaScript CSS cat'
url: 'https://guokaigdg.github.io' # your host

# nav 中文字符空格：&emsp;
nav: # 最佳体验 六个标签 且最好每个标签不超过4中文字
  首页: '/'
  标签: '/tags.html'
  时间线: '/timeline.html'
  关于博主: '/about.html'
  友情链接: '/friendLink.html'

# 博主
author: true
name: '郭凯 ma_meng'
NickName: '我家猫叫佩奇'
webtitle: 'Be happy forever'
bio: '幼稚园->小学->初中->高中->大学-> 每个人都是这样的吗 ?? '
about: true
aboutyou: ' 你的 </br>
            沙雕网友 </br>
            撸猫小能手 </br>
            手写三级残废 </br>
            从未获奖的画手 </br>
            被编程耽误的艺术家 </br>
            外卖品鉴师学习做饭ing </br>
            定焦靠手变焦靠走的摄影师 </br>
            无聊的日子就這樣，一天天過去  </br>
            新一年期待还是要有的 </br>
            1.學習Flutter </br>
            2.精通React </br>
            3.堅持每天兩點睡覺，爭取早日享受國家醫保 ​​'
portraits: '/assets/profile.jpeg' # your portraits image file path

# SNS
SNS: true
SNS-icon: #['Facebook', 'weibo', 'qq', 'github', 'Dribbble', 'Twitter', 'instagram', 'weixin', 'Codepen']
  mail: 'guokaigdg@gmail.com'
  weixin: '' # 你的微信二维码存放的地址
  qq: 'http://wpa.qq.com/msgrd?v=3&uin=972579026&site=qq&menu=yes' # 你的qq二维码存放的地址 or http://wpa.qq.com/msgrd?v=3&uin='你的QQ号'&site=qq&menu=yes
  github: 'https://github.com/guokaigdg'
  # Codepen: ''
  weibo: 'https://weibo.com/5880240752/'
  instagram: ''
  Twitter: ''
  # Dribbble: ''
  Facebook: ''
  Google: ''
  zhihu: ''
  # juejin: ''
  # twitch: ''

# 分页
paginate: 8
paginatepath: ['page:num']

# since
footer:
  since: 2018

# Markdown
markdown: kramdown
kramdown:
  input: GFM
# 代码高亮 使用rouge
highlighter: rouge
# 代码高亮主题使用pygments主题: autumn\ default\ emacs\ friendly\ manni\ murphy\ pastie\ perldoc\ tango 任选一个你喜欢的主题名称填在下面的单引号中
pygmentsTheme: 'default'

# 友情链接
friends:
  jekyll: 'https://www.jekyll.com.cn/'

# 评论 最佳体验 在disqus、livere和Gitment之间三选一
# disqus 评论
disqus: true
disqus_url: ' https://abc.disqus.com/embed.js' # https://abc.disqus.com/embed.js
# 来必力评论
livere: true
livere_uid: 'MTAyMC8zNDI2OS8xMDgwNg==' # MTAyMC8zNDI2OS8xMDgwNg==
# Gitment评论 OAuth Application
Gitment: true
Gitment_owner: 'guokaigdg'  # github用户名
Gitment_repo: 'guokaigdg.github.io'  # github博客存放的仓库名
client_id: ''  # 注册 OAuth Application 后获得的 client_id
client_secret: ''  # 注册 OAuth Application 后获得的 client_secret

# Share : weibo, qq, wechat, tencent, douban, qzone, linkedin, diandian, facebook, twitter, google
social-share: true
social-share-items: ['qq', 'wechat', 'weibo', 'twitter', 'facebook']

# 百度统计 在baidu-url里填写自己相关的url代码
baidu: true
baidu-url: ''
# 谷歌分析 在google-ID里填写自己在谷歌分析获得的追踪ID
google: false
google-ID: ''

# 博客头信息备选颜色（该部分在站点中不充当站点变量，将其写在post的头信息中用来充当页面变量）
color: rgb(154,133,255) rgb(255,90,90) rgb(255,210,32) rgb(98,170,255)
